// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: proto/chatlog.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagerService_SetLogLevel_FullMethodName        = "/chatlog.ManagerService/SetLogLevel"
	ManagerService_Run_FullMethodName                = "/chatlog.ManagerService/Run"
	ManagerService_Switch_FullMethodName             = "/chatlog.ManagerService/Switch"
	ManagerService_StartService_FullMethodName       = "/chatlog.ManagerService/StartService"
	ManagerService_StopService_FullMethodName        = "/chatlog.ManagerService/StopService"
	ManagerService_SetHTTPAddr_FullMethodName        = "/chatlog.ManagerService/SetHTTPAddr"
	ManagerService_GetDataKey_FullMethodName         = "/chatlog.ManagerService/GetDataKey"
	ManagerService_DecryptDBFiles_FullMethodName     = "/chatlog.ManagerService/DecryptDBFiles"
	ManagerService_StartAutoDecrypt_FullMethodName   = "/chatlog.ManagerService/StartAutoDecrypt"
	ManagerService_StopAutoDecrypt_FullMethodName    = "/chatlog.ManagerService/StopAutoDecrypt"
	ManagerService_RefreshSession_FullMethodName     = "/chatlog.ManagerService/RefreshSession"
	ManagerService_CommandKey_FullMethodName         = "/chatlog.ManagerService/CommandKey"
	ManagerService_CommandDecrypt_FullMethodName     = "/chatlog.ManagerService/CommandDecrypt"
	ManagerService_CommandHTTPServer_FullMethodName  = "/chatlog.ManagerService/CommandHTTPServer"
	ManagerService_GetWeChatInstances_FullMethodName = "/chatlog.ManagerService/GetWeChatInstances"
	ManagerService_GetKey_FullMethodName             = "/chatlog.ManagerService/GetKey"
	ManagerService_Decrypt_FullMethodName            = "/chatlog.ManagerService/Decrypt"
	ManagerService_Backup_FullMethodName             = "/chatlog.ManagerService/Backup"
	ManagerService_MessageCDC_FullMethodName         = "/chatlog.ManagerService/MessageCDC"
)

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ManagerService provides gRPC interface for WeChat operations
type ManagerServiceClient interface {
	SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error)
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	Switch(ctx context.Context, in *SwitchRequest, opts ...grpc.CallOption) (*SwitchResponse, error)
	StartService(ctx context.Context, in *StartServiceRequest, opts ...grpc.CallOption) (*StartServiceResponse, error)
	StopService(ctx context.Context, in *StopServiceRequest, opts ...grpc.CallOption) (*StopServiceResponse, error)
	SetHTTPAddr(ctx context.Context, in *SetHTTPAddrRequest, opts ...grpc.CallOption) (*SetHTTPAddrResponse, error)
	GetDataKey(ctx context.Context, in *GetDataKeyRequest, opts ...grpc.CallOption) (*GetDataKeyResponse, error)
	DecryptDBFiles(ctx context.Context, in *DecryptDBFilesRequest, opts ...grpc.CallOption) (*DecryptDBFilesResponse, error)
	StartAutoDecrypt(ctx context.Context, in *StartAutoDecryptRequest, opts ...grpc.CallOption) (*StartAutoDecryptResponse, error)
	StopAutoDecrypt(ctx context.Context, in *StopAutoDecryptRequest, opts ...grpc.CallOption) (*StopAutoDecryptResponse, error)
	RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*RefreshSessionResponse, error)
	CommandKey(ctx context.Context, in *CommandKeyRequest, opts ...grpc.CallOption) (*CommandKeyResponse, error)
	CommandDecrypt(ctx context.Context, in *CommandDecryptRequest, opts ...grpc.CallOption) (*CommandDecryptResponse, error)
	CommandHTTPServer(ctx context.Context, in *CommandHTTPServerRequest, opts ...grpc.CallOption) (*CommandHTTPServerResponse, error)
	GetWeChatInstances(ctx context.Context, in *GetWeChatInstancesRequest, opts ...grpc.CallOption) (*GetWeChatInstancesResponse, error)
	GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error)
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error)
	MessageCDC(ctx context.Context, in *MessageCDCRequest, opts ...grpc.CallOption) (*MessageCDCResponse, error)
}

type managerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerServiceClient(cc grpc.ClientConnInterface) ManagerServiceClient {
	return &managerServiceClient{cc}
}

func (c *managerServiceClient) SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLogLevelResponse)
	err := c.cc.Invoke(ctx, ManagerService_SetLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, ManagerService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) Switch(ctx context.Context, in *SwitchRequest, opts ...grpc.CallOption) (*SwitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchResponse)
	err := c.cc.Invoke(ctx, ManagerService_Switch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) StartService(ctx context.Context, in *StartServiceRequest, opts ...grpc.CallOption) (*StartServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartServiceResponse)
	err := c.cc.Invoke(ctx, ManagerService_StartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) StopService(ctx context.Context, in *StopServiceRequest, opts ...grpc.CallOption) (*StopServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopServiceResponse)
	err := c.cc.Invoke(ctx, ManagerService_StopService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) SetHTTPAddr(ctx context.Context, in *SetHTTPAddrRequest, opts ...grpc.CallOption) (*SetHTTPAddrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetHTTPAddrResponse)
	err := c.cc.Invoke(ctx, ManagerService_SetHTTPAddr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetDataKey(ctx context.Context, in *GetDataKeyRequest, opts ...grpc.CallOption) (*GetDataKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataKeyResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetDataKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) DecryptDBFiles(ctx context.Context, in *DecryptDBFilesRequest, opts ...grpc.CallOption) (*DecryptDBFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptDBFilesResponse)
	err := c.cc.Invoke(ctx, ManagerService_DecryptDBFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) StartAutoDecrypt(ctx context.Context, in *StartAutoDecryptRequest, opts ...grpc.CallOption) (*StartAutoDecryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartAutoDecryptResponse)
	err := c.cc.Invoke(ctx, ManagerService_StartAutoDecrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) StopAutoDecrypt(ctx context.Context, in *StopAutoDecryptRequest, opts ...grpc.CallOption) (*StopAutoDecryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopAutoDecryptResponse)
	err := c.cc.Invoke(ctx, ManagerService_StopAutoDecrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*RefreshSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshSessionResponse)
	err := c.cc.Invoke(ctx, ManagerService_RefreshSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) CommandKey(ctx context.Context, in *CommandKeyRequest, opts ...grpc.CallOption) (*CommandKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandKeyResponse)
	err := c.cc.Invoke(ctx, ManagerService_CommandKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) CommandDecrypt(ctx context.Context, in *CommandDecryptRequest, opts ...grpc.CallOption) (*CommandDecryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandDecryptResponse)
	err := c.cc.Invoke(ctx, ManagerService_CommandDecrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) CommandHTTPServer(ctx context.Context, in *CommandHTTPServerRequest, opts ...grpc.CallOption) (*CommandHTTPServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandHTTPServerResponse)
	err := c.cc.Invoke(ctx, ManagerService_CommandHTTPServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetWeChatInstances(ctx context.Context, in *GetWeChatInstancesRequest, opts ...grpc.CallOption) (*GetWeChatInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeChatInstancesResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetWeChatInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, ManagerService_Decrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupResponse)
	err := c.cc.Invoke(ctx, ManagerService_Backup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) MessageCDC(ctx context.Context, in *MessageCDCRequest, opts ...grpc.CallOption) (*MessageCDCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageCDCResponse)
	err := c.cc.Invoke(ctx, ManagerService_MessageCDC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServiceServer is the server API for ManagerService service.
// All implementations must embed UnimplementedManagerServiceServer
// for forward compatibility.
//
// ManagerService provides gRPC interface for WeChat operations
type ManagerServiceServer interface {
	SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error)
	Run(context.Context, *RunRequest) (*RunResponse, error)
	Switch(context.Context, *SwitchRequest) (*SwitchResponse, error)
	StartService(context.Context, *StartServiceRequest) (*StartServiceResponse, error)
	StopService(context.Context, *StopServiceRequest) (*StopServiceResponse, error)
	SetHTTPAddr(context.Context, *SetHTTPAddrRequest) (*SetHTTPAddrResponse, error)
	GetDataKey(context.Context, *GetDataKeyRequest) (*GetDataKeyResponse, error)
	DecryptDBFiles(context.Context, *DecryptDBFilesRequest) (*DecryptDBFilesResponse, error)
	StartAutoDecrypt(context.Context, *StartAutoDecryptRequest) (*StartAutoDecryptResponse, error)
	StopAutoDecrypt(context.Context, *StopAutoDecryptRequest) (*StopAutoDecryptResponse, error)
	RefreshSession(context.Context, *RefreshSessionRequest) (*RefreshSessionResponse, error)
	CommandKey(context.Context, *CommandKeyRequest) (*CommandKeyResponse, error)
	CommandDecrypt(context.Context, *CommandDecryptRequest) (*CommandDecryptResponse, error)
	CommandHTTPServer(context.Context, *CommandHTTPServerRequest) (*CommandHTTPServerResponse, error)
	GetWeChatInstances(context.Context, *GetWeChatInstancesRequest) (*GetWeChatInstancesResponse, error)
	GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error)
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
	Backup(context.Context, *BackupRequest) (*BackupResponse, error)
	MessageCDC(context.Context, *MessageCDCRequest) (*MessageCDCResponse, error)
	mustEmbedUnimplementedManagerServiceServer()
}

// UnimplementedManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagerServiceServer struct{}

func (UnimplementedManagerServiceServer) SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLogLevel not implemented")
}
func (UnimplementedManagerServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedManagerServiceServer) Switch(context.Context, *SwitchRequest) (*SwitchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Switch not implemented")
}
func (UnimplementedManagerServiceServer) StartService(context.Context, *StartServiceRequest) (*StartServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartService not implemented")
}
func (UnimplementedManagerServiceServer) StopService(context.Context, *StopServiceRequest) (*StopServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopService not implemented")
}
func (UnimplementedManagerServiceServer) SetHTTPAddr(context.Context, *SetHTTPAddrRequest) (*SetHTTPAddrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHTTPAddr not implemented")
}
func (UnimplementedManagerServiceServer) GetDataKey(context.Context, *GetDataKeyRequest) (*GetDataKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataKey not implemented")
}
func (UnimplementedManagerServiceServer) DecryptDBFiles(context.Context, *DecryptDBFilesRequest) (*DecryptDBFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptDBFiles not implemented")
}
func (UnimplementedManagerServiceServer) StartAutoDecrypt(context.Context, *StartAutoDecryptRequest) (*StartAutoDecryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAutoDecrypt not implemented")
}
func (UnimplementedManagerServiceServer) StopAutoDecrypt(context.Context, *StopAutoDecryptRequest) (*StopAutoDecryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAutoDecrypt not implemented")
}
func (UnimplementedManagerServiceServer) RefreshSession(context.Context, *RefreshSessionRequest) (*RefreshSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSession not implemented")
}
func (UnimplementedManagerServiceServer) CommandKey(context.Context, *CommandKeyRequest) (*CommandKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommandKey not implemented")
}
func (UnimplementedManagerServiceServer) CommandDecrypt(context.Context, *CommandDecryptRequest) (*CommandDecryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommandDecrypt not implemented")
}
func (UnimplementedManagerServiceServer) CommandHTTPServer(context.Context, *CommandHTTPServerRequest) (*CommandHTTPServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommandHTTPServer not implemented")
}
func (UnimplementedManagerServiceServer) GetWeChatInstances(context.Context, *GetWeChatInstancesRequest) (*GetWeChatInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeChatInstances not implemented")
}
func (UnimplementedManagerServiceServer) GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedManagerServiceServer) Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedManagerServiceServer) Backup(context.Context, *BackupRequest) (*BackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (UnimplementedManagerServiceServer) MessageCDC(context.Context, *MessageCDCRequest) (*MessageCDCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageCDC not implemented")
}
func (UnimplementedManagerServiceServer) mustEmbedUnimplementedManagerServiceServer() {}
func (UnimplementedManagerServiceServer) testEmbeddedByValue()                        {}

// UnsafeManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerServiceServer will
// result in compilation errors.
type UnsafeManagerServiceServer interface {
	mustEmbedUnimplementedManagerServiceServer()
}

func RegisterManagerServiceServer(s grpc.ServiceRegistrar, srv ManagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagerService_ServiceDesc, srv)
}

func _ManagerService_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_SetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).SetLogLevel(ctx, req.(*SetLogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_Switch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Switch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_Switch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Switch(ctx, req.(*SwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_StartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).StartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_StartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).StartService(ctx, req.(*StartServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_StopService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).StopService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_StopService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).StopService(ctx, req.(*StopServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_SetHTTPAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHTTPAddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).SetHTTPAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_SetHTTPAddr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).SetHTTPAddr(ctx, req.(*SetHTTPAddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetDataKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetDataKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetDataKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetDataKey(ctx, req.(*GetDataKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_DecryptDBFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptDBFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).DecryptDBFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_DecryptDBFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).DecryptDBFiles(ctx, req.(*DecryptDBFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_StartAutoDecrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAutoDecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).StartAutoDecrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_StartAutoDecrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).StartAutoDecrypt(ctx, req.(*StartAutoDecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_StopAutoDecrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAutoDecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).StopAutoDecrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_StopAutoDecrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).StopAutoDecrypt(ctx, req.(*StopAutoDecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_RefreshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).RefreshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_RefreshSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).RefreshSession(ctx, req.(*RefreshSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_CommandKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).CommandKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_CommandKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).CommandKey(ctx, req.(*CommandKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_CommandDecrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandDecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).CommandDecrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_CommandDecrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).CommandDecrypt(ctx, req.(*CommandDecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_CommandHTTPServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandHTTPServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).CommandHTTPServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_CommandHTTPServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).CommandHTTPServer(ctx, req.(*CommandHTTPServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetWeChatInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeChatInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetWeChatInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetWeChatInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetWeChatInstances(ctx, req.(*GetWeChatInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetKey(ctx, req.(*GetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_Decrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_Backup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_MessageCDC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageCDCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).MessageCDC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_MessageCDC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).MessageCDC(ctx, req.(*MessageCDCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagerService_ServiceDesc is the grpc.ServiceDesc for ManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatlog.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLogLevel",
			Handler:    _ManagerService_SetLogLevel_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _ManagerService_Run_Handler,
		},
		{
			MethodName: "Switch",
			Handler:    _ManagerService_Switch_Handler,
		},
		{
			MethodName: "StartService",
			Handler:    _ManagerService_StartService_Handler,
		},
		{
			MethodName: "StopService",
			Handler:    _ManagerService_StopService_Handler,
		},
		{
			MethodName: "SetHTTPAddr",
			Handler:    _ManagerService_SetHTTPAddr_Handler,
		},
		{
			MethodName: "GetDataKey",
			Handler:    _ManagerService_GetDataKey_Handler,
		},
		{
			MethodName: "DecryptDBFiles",
			Handler:    _ManagerService_DecryptDBFiles_Handler,
		},
		{
			MethodName: "StartAutoDecrypt",
			Handler:    _ManagerService_StartAutoDecrypt_Handler,
		},
		{
			MethodName: "StopAutoDecrypt",
			Handler:    _ManagerService_StopAutoDecrypt_Handler,
		},
		{
			MethodName: "RefreshSession",
			Handler:    _ManagerService_RefreshSession_Handler,
		},
		{
			MethodName: "CommandKey",
			Handler:    _ManagerService_CommandKey_Handler,
		},
		{
			MethodName: "CommandDecrypt",
			Handler:    _ManagerService_CommandDecrypt_Handler,
		},
		{
			MethodName: "CommandHTTPServer",
			Handler:    _ManagerService_CommandHTTPServer_Handler,
		},
		{
			MethodName: "GetWeChatInstances",
			Handler:    _ManagerService_GetWeChatInstances_Handler,
		},
		{
			MethodName: "GetKey",
			Handler:    _ManagerService_GetKey_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _ManagerService_Decrypt_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _ManagerService_Backup_Handler,
		},
		{
			MethodName: "MessageCDC",
			Handler:    _ManagerService_MessageCDC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chatlog.proto",
}
